host: login.salesforce.com        # Use test.salesforce.com for sandbox
client_secret: 5587993940227999074         # This is the Consumer Secret from Salesforce
client_id: 3MVG9y6x0357Hledlw0Op2Vcbey_xXD3gqwk.D9ApXFeNioQCOda082RjQegBOrMyJ4CispsJoJyDAFbc6dIR     # This is the Consumer Key from Salesforce
#sobject_module: SFDC_Models       # This is not needed since we are using the databasedotcom-rails gem.
debugging: false                  # Can be useful while developing
username: ricas071340318457207@gmail.com
password: pezzep0709fdl4aPqTzMxNN13QAVQi6g #Password plus token from salesforce